import { Material } from 'org.bukkit';

// prettier-ignore
export const FoodInfo = new Map<Material, { f: number; s: number }>([
  [Material.APPLE,            { f: 4,   s: 2.4    }],
  [Material.BAKED_POTATO,     { f: 5,   s: 6      }],
  [Material.BEETROOT,         { f: 1,   s: 1.2    }],
  [Material.BEETROOT_SOUP,    { f: 6,   s: 7.2    }],
  [Material.BREAD,            { f: 5,   s: 6      }],
  [Material.CARROT,           { f: 3,   s: 3.6    }],
  [Material.CHORUS_FRUIT,     { f: 4,   s: 2.4    }],
  [Material.COOKED_CHICKEN,   { f: 6,   s: 7.2    }],
  [Material.COOKED_COD,       { f: 5,   s: 6      }],
  [Material.COOKED_MUTTON,    { f: 6,   s: 9.6    }],
  [Material.COOKED_PORKCHOP,  { f: 8,   s: 12.8   }],
  [Material.COOKED_RABBIT,    { f: 5,   s: 6      }],
  [Material.COOKED_SALMON,    { f: 6,   s: 9.6    }],
  [Material.COOKIE,           { f: 2,   s: 0.4    }],
  [Material.DRIED_KELP,       { f: 1,   s: 0.6    }],
  [Material.GOLDEN_CARROT,    { f: 6,   s: 14.4   }],
  [Material.HONEY_BOTTLE,     { f: 6,   s: 1.2    }],
  [Material.MELON_SLICE,      { f: 2,   s: 1.2    }],
  [Material.MUSHROOM_STEW,    { f: 6,   s: 7.2    }],
  //[Material.POISONOUS_POTATO, { f: 2,   s: 1.2    }], 
  [Material.POTATO,           { f: 1,   s: 0.6    }],
  //[Material.PUFFERFISH,       { f: 1,   s: 0.2    }],
  [Material.PUMPKIN_PIE,      { f: 8,   s: 4.8    }],
  [Material.RABBIT_STEW,      { f: 10,  s: 12     }],
  [Material.BEEF,             { f: 3,   s: 1.8    }],
  [Material.CHICKEN,          { f: 2,   s: 1.2    }],
  [Material.COD,              { f: 2,   s: 0.4    }],
  [Material.MUTTON,           { f: 2,   s: 1.2    }],
  [Material.PORKCHOP,         { f: 3,   s: 1.8    }],
  [Material.RABBIT,           { f: 3,   s: 1.8    }],
  [Material.SALMON,           { f: 2,   s: 0.4    }],
  //[Material.ROTTEN_FLESH,     { f: 4,   s: 0.8    }],
  //[Material.SPIDER_EYE,       { f: 2,   s: 3.2    }],
  [Material.COOKED_BEEF,      { f: 8,   s: 12.8   }],
  //[Material.SUSPICIOUS_STEW,  { f: 6,   s: 7.2    }],
  [Material.SWEET_BERRIES,    { f: 2,   s: 0.4    }],
  [Material.TROPICAL_FISH,    { f: 1,   s: 0.2    }],
]);
