require('./common/polyfill');
require('./common/entities/index');
require('./misc/index');
require('./mining/index');
require('./mobs/index');
require('./combat/index');
require('./hydration/index');
require('./food/index');
require('./farming/index');
require('./health/index');
require('./games/index');
require('./instruments/index');
require('./blacksmith/index');
require('./admin/index');
require('./crafting/index');
require('./chat/index');
require('./economy/index');
require('./death/index');
require('./locks/index');
require('./profession/index');
require('./stats/index');

log.info('Valtakausi systems loaded');
