require('./misc/index');
require('./mining/index');
require('./chess/index');
require('./mobs/index');
require('./combat/index');
require('./hydration/index');
require('./food/index');
require('./farming/index');
require('./football/index');
